const mongoose = require("mongoose");

const marriageSchema = new mongoose.Schema({
  sacrament: { type: String, default: "Marriage" },
  dateOfWedding: { type: String, required: true },
  timeOfWedding: { type: String, required: true },
  groomName: { type: String, required: true },
  groomMiddleName: { type: String, required: true },
  groomSurname: { type: String, required: true },
  groomDOB: { type: String, required: true },
  groomAge: { type: String, required: true },
  groomPOB: { type: String, required: true },
  groomResidence: { type: String, required: true },
  groomFatherName: { type: String, required: true },
  groomMotherMaidenName: { type: String, required: true },
  groomCP: { type: String, required: true },
  brideName: { type: String, required: true },
  brideMiddleName: { type: String, required: true },
  brideSurname: { type: String, required: true },
  brideDOB: { type: String, required: true },
  brideAge: { type: String, required: true },
  bridePOB: { type: String, required: true },
  brideResidence: { type: String, required: true },
  brideFatherName: { type: String, required: true },
  brideMotherMaidenName: { type: String, required: true },
  brideCP: { type: String, required: true },
  groomMarriageLicense: String,
  groomBaptismalCert: String,
  groomConfirmationCert: String,
  groomMarriageBannsPermission: String,
  brideMarriageLicense: String,
  brideBaptismalCert: String,
  brideConfirmationCert: String,
  brideMarriageBannsPermission: String,
  interviewDate: String,
  interviewTime: String,
  seminarDate: String,
  seminarTime: String,
  sponsors: [String],
  groomSignature: String,
  brideSignature: String,
  status: { type: String, default: "pending" },
  paymentStatus: { type: String, default: "pending" },
  fee: { type: Number, default: 5000 },
  submittedByEmail: { type: String, required: true },
  requestNumber: { type: String, required: true },
  cancellation_reason: String,
  rejection_reason: String,
  cancelled_by: String,
  rejected_by: String,
  cancelled_at: Date,
  rejected_at: Date,
  paymentDate: String,
  paymentMethod: String,
  paymentReference: String,
  paymentNotes: String,
  createdAt: { type: Date, default: Date.now },
  lastUpdated: { type: Date, default: Date.now }
}, { suppressReservedKeysWarning: true });

module.exports = mongoose.model("MarriageRequest", marriageSchema, "marriagerequests");